site_name: Robot Faces
site_description: 'Resources for teaching drawing of robot faces with microcontrollers and MicroPython to robotics students.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/robot-faces'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Lessons:
    - Introduction: lessons/index.md
    - Screen Coordinates: lessons/screen-coordinates.md
    - Basic Drawing Commands: lessons/drawing-commands.md
    - Ellipse: lessons/ellipse.md
    - Polygon: lessons/polygon.md
    - Basic Face Layouts: lessons/basic-face-layouts.md
    - Eye Scanner: lessons/eye-scanner.md
    - Interactions: lessons/interactions.md
    - lessons/blit-commands.md
    - lessons/multiple-threads.md
    - lessons/eyebrows.md

  - parts-lists.md
  - about.md
  - Contact: contact.md
  - Glossary: glossary.md
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.jpg
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true

extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-DS16K4YVRR

